# Generated by Django 3.0.3 on 2020-05-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bags',
            new_name='Bag',
        ),
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Shoe',
        ),
    ]
