# Generated by Django 3.0.3 on 2020-05-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20200506_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('men', 'men'), ('female', 'female'), ('watches', 'watches'), ('bag', 'bag'), ('shoes', 'shoes')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
        migrations.DeleteModel(
            name='Men',
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
        migrations.DeleteModel(
            name='Watches',
        ),
        migrations.DeleteModel(
            name='Women',
        ),
    ]
