# Generated by Django 3.0.3 on 2020-05-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='des', to='sections.Product'),
        ),
    ]
