# Generated by Django 3.0.3 on 2020-05-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_auto_20200513_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'men'), ('female', 'female'), ('bag', 'bag'), ('shoes', 'shoes'), ('watch', 'watch')], max_length=100),
        ),
    ]
