# Generated by Django 3.0.3 on 2020-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0009_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
