# Generated by Django 3.0.3 on 2020-05-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0012_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
