# Generated by Django 3.0.3 on 2020-05-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0014_auto_20200522_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
