# Generated by Django 3.0.3 on 2020-06-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0017_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sections.Customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sections.Customer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sections.Customer'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='guest',
            field=models.BooleanField(default=False),
        ),
    ]
